import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowRight, BedDouble, MapPin, Users } from "lucide-react";
import { ShowcaseSwitcher } from "@/features/showcase/components/showcase-switcher";
import { conceptImages, stays } from "@/features/stays/data/demo-data";
import { formatCurrency } from "@/shared/lib/format";

export function EditorialTemplate() {
  return <main className="showcase-root min-h-screen bg-[#f3eee5] pb-32 text-[#19322c]">
    <ShowcaseSwitcher current="tinh-lang" />
    <header className="mx-auto flex h-24 w-[min(1420px,calc(100%-40px))] items-center justify-between border-b border-[#19322c]/15"><Link href="/mau/tinh-lang" className="font-serif text-3xl font-semibold tracking-[-.055em]">Lago.</Link><nav className="hidden items-center gap-8 text-[.66rem] font-bold uppercase tracking-[.16em] md:flex"><Link href="#collection">Các căn nhà</Link><Link href="/trai-nghiem">Trải nghiệm</Link><Link href="/ve-lago">Câu chuyện</Link></nav><Link href="/dat-phong" className="border-b border-[#19322c] pb-1 text-xs font-bold uppercase tracking-[.12em]">Kiểm tra lịch</Link></header>

    <section className="mx-auto grid min-h-[calc(100svh-96px)] w-[min(1420px,calc(100%-40px))] items-center gap-8 py-10 lg:grid-cols-[.82fr_1.18fr] lg:py-14">
      <div className="relative z-10 lg:pr-8"><p className="text-[.65rem] font-bold uppercase tracking-[.24em] text-[#a36349]">Lago Journal · Issue 01</p><h1 className="mt-8 font-serif text-[4.2rem] font-medium leading-[.82] tracking-[-.065em] sm:text-[6.5rem] lg:text-[8rem]">The art of<br /><i className="font-normal">quiet living.</i></h1><p className="mt-10 max-w-md text-sm leading-7 text-[#19322c]/58">Bốn căn nhà giữa thiên nhiên, dành cho những ngày bạn muốn bước chậm lại và ở gần nhau hơn.</p><div className="mt-8 flex items-center gap-6"><Link href="/dat-phong" className="inline-flex min-h-14 items-center gap-4 rounded-full bg-[#19322c] px-6 text-sm font-bold text-white">Tìm căn của bạn <ArrowRight className="h-4 w-4" /></Link><a href="#collection" aria-label="Cuộn đến bộ sưu tập" className="grid h-14 w-14 place-items-center rounded-full border border-[#19322c]/25"><ArrowDownRight className="h-5 w-5" /></a></div></div>
      <div className="relative min-h-[560px] lg:min-h-[720px]"><div className="absolute inset-y-0 right-0 w-[88%] overflow-hidden rounded-t-[220px]"><Image src={conceptImages.detail1} alt="Không gian Lago phong cách editorial" fill priority sizes="(max-width:1024px) 100vw, 58vw" className="object-cover" /><div className="absolute inset-0 bg-[#19322c]/8" /></div><div className="absolute bottom-10 left-0 max-w-[230px] border border-[#19322c]/15 bg-[#f3eee5]/94 p-6 backdrop-blur"><p className="font-serif text-2xl leading-tight">“Một nơi để thời gian thôi thúc giục.”</p><p className="mt-5 text-[.58rem] font-bold uppercase tracking-[.18em] text-[#a36349]">Lago philosophy</p></div><span className="absolute right-5 top-5 rounded-full border border-white/50 bg-white/25 px-3 py-1.5 text-[.56rem] font-bold uppercase tracking-widest text-white backdrop-blur">Ảnh concept</span></div>
    </section>

    <section className="border-y border-[#19322c]/15 py-8"><div className="mx-auto grid w-[min(1420px,calc(100%-40px))] gap-5 text-center text-[.62rem] font-bold uppercase tracking-[.18em] text-[#19322c]/45 sm:grid-cols-3"><span>04 private houses</span><span>Nature outside · comfort inside</span><span>Stay slow · stay close</span></div></section>

    <section id="collection" className="mx-auto w-[min(1420px,calc(100%-40px))] py-24 sm:py-32"><div className="grid items-end gap-8 lg:grid-cols-[1fr_.55fr]"><div><p className="text-[.65rem] font-bold uppercase tracking-[.18em] text-[#a36349]">The private collection</p><h2 className="mt-5 max-w-4xl font-serif text-5xl font-medium leading-[1.05] tracking-[-.035em] sm:text-7xl">Mỗi căn nhà,<br /><i>một khoảng riêng.</i></h2></div><p className="text-sm leading-7 text-[#19322c]/55">Chọn không gian theo người đồng hành, nhịp nghỉ và cách bạn muốn thức dậy mỗi sáng.</p></div>
      <div className="mt-16 grid gap-10 md:grid-cols-2">{stays.map((stay, index) => <Link href={`/luu-tru/${stay.slug}`} key={stay.id} className={`group ${index % 2 ? "md:mt-24" : ""}`}><div className="relative aspect-[4/5] overflow-hidden bg-[#ded5c8]"><Image src={stay.image} alt={`${stay.name} - ảnh concept`} fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover transition duration-700 group-hover:scale-[1.025]" /><span className="absolute left-4 top-4 rounded-full bg-[#f3eee5]/92 px-3 py-1.5 text-[.58rem] font-bold uppercase tracking-wider">0{index + 1}</span></div><div className="mt-5 flex items-start justify-between gap-6 border-b border-[#19322c]/15 pb-5"><div><p className="text-[.6rem] font-bold uppercase tracking-[.18em] text-[#a36349]">{stay.location}</p><h3 className="mt-2 font-serif text-4xl font-medium tracking-[-.04em]">{stay.name}</h3><div className="mt-3 flex gap-4 text-xs text-[#19322c]/48"><span className="flex items-center gap-1.5"><Users className="h-3.5 w-3.5" />{stay.maxGuests}</span><span className="flex items-center gap-1.5"><BedDouble className="h-3.5 w-3.5" />{stay.bedrooms} phòng</span><span className="flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5" />{stay.highlights[0]}</span></div></div><div className="text-right text-[.62rem] uppercase tracking-wider text-[#19322c]/42">Từ<br /><strong className="mt-1 block text-sm text-[#19322c]">{formatCurrency(stay.basePrice)}</strong></div></div></Link>)}</div>
    </section>

    <section className="mx-auto w-[min(1420px,calc(100%-24px))] bg-[#19322c] px-6 py-20 text-center text-white sm:px-12 sm:py-28"><p className="text-[.64rem] font-bold uppercase tracking-[.2em] text-[#dbc6a9]">Your quiet days await</p><h2 className="mx-auto mt-6 max-w-4xl font-serif text-5xl font-medium leading-[1.08] tracking-[-.035em] sm:text-7xl">Để Lago giữ lại<br /><i>một khoảng yên cho bạn.</i></h2><Link href="/dat-phong" className="mt-9 inline-flex min-h-14 items-center gap-3 rounded-full bg-white px-7 text-sm font-bold text-[#19322c]">Chọn ngày lưu trú <ArrowRight className="h-4 w-4" /></Link></section>
  </main>;
}
