import Link from "next/link";
import { ArrowRight, Phone, Plus, ShieldCheck } from "lucide-react";
import { showcaseFaqs } from "@/features/showcase/data/showcase-content";

type Mood = "editorial" | "cinematic" | "organic";
type Policy = readonly [string, string];

function Answer({ text }: { text: string }) {
  return <div className="grid grid-rows-[0fr] transition-[grid-template-rows] duration-500 ease-out group-open:grid-rows-[1fr]"><div className="overflow-hidden"><p className="max-w-2xl pb-1 pt-4 text-sm leading-7 opacity-58">{text}</p></div></div>;
}

export function TemplateFaqSection({ mood, policyHref }: { mood: Mood; policyHref: string }) {
  if (mood === "cinematic") return <section className="mx-auto grid w-[min(1380px,calc(100%-40px))] gap-12 py-20 sm:py-28 lg:grid-cols-[.38fr_1fr]">
    <aside className="h-fit border-l border-[#e5c59c]/35 pl-6 lg:sticky lg:top-28"><p className="text-[.62rem] font-bold uppercase tracking-[.22em] text-[#e5c59c]">Hỗ trợ trực tiếp</p><p className="mt-6 max-w-xs font-serif text-3xl font-medium leading-tight">Một cuộc trò chuyện ngắn có thể giúp bạn chọn đúng căn.</p><a href="tel:0900000000" className="mt-7 inline-flex items-center gap-3 text-sm font-bold text-[#e5c59c]"><Phone className="h-4 w-4" />0900 000 000</a></aside>
    <div className="border-t border-white/12">{showcaseFaqs.map(([question, answer], index) => <details key={question} className="group border-b border-white/12 py-7"><summary className="flex cursor-pointer list-none items-start gap-5"><span className="pt-1 text-[.62rem] font-bold text-[#e5c59c]">0{index + 1}</span><span className="flex-1 font-serif text-2xl font-medium leading-tight sm:text-3xl">{question}</span><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-white/15 transition duration-300 group-open:rotate-45 group-open:border-[#e5c59c] group-open:text-[#e5c59c]"><Plus className="h-4 w-4" /></span></summary><div className="pl-11 text-white/72"><Answer text={answer} /></div></details>)}<Link href={policyHref} className="mt-9 inline-flex items-center gap-3 text-sm font-bold text-[#e5c59c]">Đọc toàn bộ chính sách <ArrowRight className="h-4 w-4" /></Link></div>
  </section>;

  if (mood === "organic") return <section className="mx-auto w-[min(1280px,calc(100%-28px))] py-20 sm:py-28">
    <div className="mb-9 flex flex-col gap-6 rounded-[34px] bg-[#21483d] p-7 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[.6rem] font-extrabold uppercase tracking-[.14em] text-[#f7cf58]">Bạn cứ hỏi nhé</p><p className="mt-3 text-2xl font-extrabold">Lago trả lời rõ trước khi bạn lên đường.</p></div><a href="tel:0900000000" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#f7cf58] px-6 text-sm font-extrabold text-[#21483d]"><Phone className="h-4 w-4" />Gọi Lago</a></div>
    <div className="grid gap-4 md:grid-cols-2">{showcaseFaqs.map(([question, answer], index) => <details key={question} className={`group h-fit rounded-[30px] p-6 shadow-[0_16px_45px_rgba(33,72,61,.07)] ${index === 1 ? "bg-[#f7cf58]" : index === 2 ? "bg-[#dce9c6]" : "bg-white"}`}><summary className="flex cursor-pointer list-none items-start gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#21483d] text-[.62rem] font-extrabold text-white">0{index + 1}</span><span className="flex-1 text-lg font-extrabold leading-snug">{question}</span><Plus className="mt-2 h-5 w-5 shrink-0 transition duration-300 group-open:rotate-45" /></summary><div className="pl-[52px]"><Answer text={answer} /></div></details>)}</div><Link href={policyHref} className="mt-8 inline-flex items-center gap-2 rounded-full border-2 border-[#21483d]/14 px-6 py-3 text-sm font-extrabold">Xem chính sách lưu trú <ArrowRight className="h-4 w-4" /></Link>
  </section>;

  return <section className="mx-auto grid w-[min(1120px,calc(100%-40px))] gap-12 py-20 sm:py-28 lg:grid-cols-[.55fr_1fr]">
    <aside className="h-fit lg:sticky lg:top-28"><p className="text-[.62rem] font-bold uppercase tracking-[.18em] text-[#a36349]">Cần thêm thông tin?</p><p className="mt-6 max-w-sm font-serif text-3xl font-medium leading-tight">Chúng mình sẵn sàng lắng nghe trước khi bạn quyết định.</p><p className="mt-4 max-w-sm text-sm leading-7 opacity-55">Gọi hoặc nhắn Zalo, đội ngũ Lago sẽ tư vấn theo nhu cầu của từng đoàn.</p><a href="tel:0900000000" className="mt-7 inline-flex items-center gap-2 border-b border-[#19322c] pb-1 text-sm font-bold"><Phone className="h-4 w-4" />0900 000 000</a></aside>
    <div className="border-t border-[#19322c]/15">{showcaseFaqs.map(([question, answer], index) => <details key={question} className="group border-b border-[#19322c]/15 py-7"><summary className="flex cursor-pointer list-none items-start gap-5"><span className="pt-1 text-[.6rem] font-bold text-[#a36349]">0{index + 1}</span><span className="flex-1 font-serif text-2xl font-medium leading-tight">{question}</span><Plus className="mt-1 h-5 w-5 shrink-0 transition duration-300 group-open:rotate-45" /></summary><div className="pl-10"><Answer text={answer} /></div></details>)}<Link href={policyHref} className="mt-8 inline-flex items-center gap-2 text-sm font-bold">Đọc chính sách lưu trú <ArrowRight className="h-4 w-4" /></Link></div>
  </section>;
}

export function TemplatePolicySection({ mood, policies }: { mood: Mood; policies: readonly Policy[] }) {
  if (mood === "cinematic") return <section className="mx-auto w-[min(1320px,calc(100%-40px))] py-20 sm:py-28"><div className="grid gap-px overflow-hidden border border-white/12 bg-white/12 md:grid-cols-2">{policies.map(([title, text], index) => <article key={title} className="relative min-h-[300px] overflow-hidden bg-[#07130f] p-8"><span className="absolute -right-2 -top-8 font-serif text-[9rem] leading-none text-white/[.025]">0{index + 1}</span><ShieldCheck className="h-6 w-6 text-[#e5c59c]" /><p className="mt-12 text-[.58rem] font-bold uppercase tracking-[.2em] text-[#e5c59c]">House rule · 0{index + 1}</p><h2 className="mt-4 font-serif text-3xl font-medium">{title}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/48">{text}</p></article>)}</div></section>;

  if (mood === "organic") {
    const colors = ["bg-white", "bg-[#f7cf58]", "bg-[#dce9c6]", "bg-[#f18b68]"];
    return <section className="mx-auto w-[min(1280px,calc(100%-28px))] py-20 sm:py-28"><div className="grid gap-4 md:grid-cols-2">{policies.map(([title, text], index) => <article key={title} className={`min-h-[280px] rounded-[36px] p-7 shadow-[0_18px_55px_rgba(33,72,61,.08)] ${colors[index]}`}><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#21483d] text-[.62rem] font-extrabold text-white">0{index + 1}</span><ShieldCheck className="h-6 w-6" /></div><h2 className="mt-12 text-2xl font-extrabold">{title}</h2><p className="mt-4 max-w-lg text-sm font-medium leading-7 opacity-58">{text}</p></article>)}</div></section>;
  }

  return <section className="mx-auto w-[min(900px,calc(100%-40px))] py-20 sm:py-28"><div className="mb-8 border-b border-[#19322c]/15 pb-8"><p className="font-serif text-3xl font-medium">Những điều nhỏ giúp kỳ nghỉ nhẹ nhàng hơn cho tất cả mọi người.</p></div>{policies.map(([title, text], index) => <article key={title} className="grid gap-5 border-b border-[#19322c]/15 py-9 sm:grid-cols-[70px_1fr]"><span className="text-xs font-bold text-[#a36349]">0{index + 1}</span><div><h2 className="font-serif text-3xl font-medium">{title}</h2><p className="mt-4 text-sm leading-7 opacity-58">{text}</p></div></article>)}</section>;
}
