import Image from "next/image";
import { ShowcaseLink as Link } from "@/features/showcase/site/showcase-link";
import { ArrowRight, Bath, Coffee, Heart, Leaf, Plus, Sparkles, Sun, Users } from "lucide-react";
import { ShowcaseSwitcher } from "@/features/showcase/components/showcase-switcher";
import { TemplateExperienceLayer } from "@/features/showcase/components/template-experience-layer";
import { guestStories, showcaseFaqs } from "@/features/showcase/data/showcase-content";
import { conceptImages, stays } from "@/features/stays/data/demo-data";
import { formatCurrency } from "@/shared/lib/format";
import { TemplateFooter, TemplateHeader, type CompleteTemplateConfig } from "@/features/showcase/site/complete-template-site";

export function SongDongHome({ config }: { config: CompleteTemplateConfig }) {
  return <main className="showcase-root min-h-screen overflow-hidden bg-[#eef1e5] text-[#21483d]">
    <TemplateExperienceLayer mood="organic" />
    <ShowcaseSwitcher current="song-dong" />
    <TemplateHeader config={config} />
    <div className="relative"><span className="absolute -right-32 -top-32 h-[420px] w-[420px] rounded-full bg-[#f18b68] opacity-90" /><span className="absolute left-[42%] top-28 h-28 w-28 rounded-full bg-[#f7cf58]" />

      <section className="relative z-[1] mx-auto grid min-h-[calc(100svh-76px)] w-[min(1380px,calc(100%-28px))] items-center gap-10 py-12 lg:grid-cols-[.85fr_1.15fr] lg:py-16"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#dce9c6] px-4 py-2 text-[.65rem] font-extrabold uppercase tracking-[.12em]"><Sparkles className="h-4 w-4" /> Nơi vui giữa thiên nhiên</span><h1 className="mt-7 text-[clamp(3.45rem,16.5vw,6.5rem)] font-extrabold leading-[.96] tracking-[-.05em] lg:text-[8rem]">Ở xanh.<br />Cười <span className="relative text-[#e66e4c]">thật lâu.<svg className="absolute -bottom-3 left-0 w-full" viewBox="0 0 300 18" fill="none"><path d="M4 12C79 2 210 2 296 10" stroke="#f7cf58" strokeWidth="10" strokeLinecap="round" /></svg></span></h1><p className="mt-9 max-w-lg text-base font-medium leading-7 text-[#21483d]/62">Một bộ sưu tập nhà nguyên căn đủ riêng tư để nghỉ ngơi, đủ vui để mọi người thật sự gần nhau.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`${config.basePath}/dat-phong`} className="inline-flex min-h-14 items-center gap-3 rounded-full bg-[#21483d] px-7 text-sm font-extrabold text-white">Tìm nhà hợp gu <ArrowRight className="h-4 w-4" /></Link><a href="#happy-houses" className="inline-flex min-h-14 items-center rounded-full border-2 border-[#21483d]/16 px-6 text-sm font-extrabold">Khám phá 4 căn</a></div></div>
        <div className="relative min-h-[570px] lg:min-h-[700px]"><div className="organic-hero absolute inset-0 overflow-hidden"><Image src={conceptImages.experience} alt="Kỳ nghỉ sống động tại Lago - ảnh minh họa" fill priority sizes="(max-width:1024px) 100vw, 58vw" className="object-cover" /></div><div className="absolute left-0 top-14 rotate-[-7deg] rounded-[24px] bg-white p-4 shadow-2xl"><Heart className="h-5 w-5 fill-[#f18b68] text-[#f18b68]" /><p className="mt-3 text-sm font-extrabold">100% riêng tư</p><p className="mt-1 text-[.62rem] text-[#21483d]/48">Không chia sẻ với khách lạ</p></div><div className="absolute bottom-10 right-0 rotate-[5deg] rounded-[26px] bg-[#f7cf58] p-5 shadow-2xl"><Sun className="h-7 w-7" /><p className="mt-3 text-lg font-extrabold leading-tight">Nắng, cây<br />và người mình thương.</p></div><span className="absolute right-6 top-6 grid h-20 w-20 place-items-center rounded-full bg-[#21483d] text-center text-[.58rem] font-extrabold uppercase tracking-wider text-white">Ảnh<br />minh họa</span></div>
      </section>
    </div>

    <section className="bg-[#21483d] py-5 text-[#eef1e5]"><div className="organic-marquee flex w-max gap-8 whitespace-nowrap text-2xl font-extrabold tracking-[-.04em]"><span>Nhà riêng ✦ Bếp xinh ✦ Nhiều cây ✦ Đủ chỗ cho nhau ✦</span><span>Nhà riêng ✦ Bếp xinh ✦ Nhiều cây ✦ Đủ chỗ cho nhau ✦</span></div></section>

    <section id="happy-houses" className="mx-auto w-[min(1380px,calc(100%-28px))] py-24 sm:py-32"><div className="grid gap-7 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-[.68rem] font-extrabold uppercase tracking-[.14em] text-[#e66e4c]">Chọn căn hợp niềm vui</p><h2 className="mt-5 text-5xl font-extrabold leading-[1.02] tracking-[-.04em] sm:text-7xl">Mỗi chuyến đi<br />một <i className="font-serif font-medium">cảm xúc riêng.</i></h2></div><p className="max-w-xl text-sm font-medium leading-7 text-[#21483d]/58 lg:ml-auto">Không cần tìm căn đẹp nhất. Chỉ cần tìm căn khiến mọi người trong chuyến đi đều thấy: “Đúng chỗ này rồi!”</p></div>
      <div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-12">{stays.map((stay, index) => <Link href={`${config.basePath}/luu-tru/${stay.slug}`} key={stay.id} className={`group overflow-hidden rounded-[34px] border border-[#21483d]/8 bg-white p-3 shadow-[0_18px_50px_rgba(33,72,61,.07)] transition hover:-translate-y-2 ${index === 0 || index === 3 ? "lg:col-span-7" : "lg:col-span-5"}`}><div className={`relative overflow-hidden rounded-[26px] ${index === 0 || index === 3 ? "aspect-[16/10]" : "aspect-[4/3]"}`}><Image src={stay.image} alt={`${stay.name} - ảnh minh họa`} fill sizes="(max-width:1024px) 50vw, 55vw" className="object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-white px-3 py-1.5 text-[.6rem] font-extrabold uppercase tracking-wider">{stay.badge}</span></div><div className="p-3 pb-4 pt-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[.62rem] font-extrabold uppercase tracking-[.14em] text-[#e66e4c]">{stay.location}</p><h3 className="mt-2 text-3xl font-extrabold tracking-[-.045em]">{stay.name}</h3></div><span className="grid h-12 w-12 place-items-center rounded-full bg-[#dce9c6] transition group-hover:rotate-12 group-hover:bg-[#f7cf58]"><ArrowRight className="h-5 w-5" /></span></div><p className="mt-3 text-sm leading-6 text-[#21483d]/52">{stay.description}</p><div className="mt-5 flex flex-wrap items-center gap-4 border-t border-[#21483d]/8 pt-4 text-xs font-bold"><span className="flex items-center gap-1.5"><Users className="h-4 w-4" />{stay.maxGuests} khách</span><span className="flex items-center gap-1.5"><Bath className="h-4 w-4" />{stay.bathrooms} phòng tắm</span><span className="ml-auto">Từ {formatCurrency(stay.basePrice)}</span></div></div></Link>)}</div>
    </section>

    <section className="mx-auto grid w-[min(1380px,calc(100%-28px))] gap-4 pb-24 sm:grid-cols-3">{[[Coffee,"Sáng không vội","Pha trà, mở cửa và để nắng tự tìm vào."],[Leaf,"Xanh là hàng xóm","Mỗi căn đều có một khoảng thiên nhiên của riêng mình."],[Heart,"Gần nhau hơn","Bếp và bàn ăn dành cho những câu chuyện thật dài."]].map(([Icon,title,text],index)=>{const C=Icon as typeof Coffee;return <article key={String(title)} className={`rounded-[34px] p-7 ${index===0?"bg-[#f7cf58]":index===1?"bg-[#dce9c6]":"bg-[#f18b68]"}`}><C className="h-7 w-7" /><span className="mt-12 block text-[.62rem] font-extrabold uppercase tracking-[.16em]">0{index+1}</span><h3 className="mt-3 text-2xl font-extrabold tracking-[-.04em]">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-[#21483d]/62">{String(text)}</p></article>})}</section>

    <section className="bg-[#dce9c6] py-24 sm:py-32"><div className="mx-auto w-[min(1380px,calc(100%-28px))]"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-[.66rem] font-extrabold uppercase tracking-[.14em] text-[#e66e4c]">Khách vui · chuyện đáng nhớ</p><h2 className="mt-4 text-5xl font-extrabold leading-[1.02] tracking-[-.04em] sm:text-7xl">Mang về nhiều hơn<br />một bộ ảnh đẹp.</h2></div><span className="grid h-20 w-20 shrink-0 place-items-center rounded-full bg-[#f7cf58] text-3xl">☺</span></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{guestStories.map((story,index)=><blockquote key={story.name} className={`rounded-[32px] p-7 ${index===1?"bg-[#f18b68]":index===2?"bg-[#21483d] text-white":"bg-white"}`}><div className="flex gap-1 text-xl text-[#f7cf58]">★★★★★</div><p className="mt-8 text-lg font-bold leading-7">“{story.quote}”</p><footer className={`mt-8 border-t pt-5 text-xs font-bold ${index===2?"border-white/15 text-white/55":"border-[#21483d]/10 text-[#21483d]/52"}`}>{story.name}<span className="mt-1 block font-medium">{story.stay}</span></footer></blockquote>)}</div></div></section>

    <section className="mx-auto grid w-[min(1380px,calc(100%-28px))] gap-10 py-24 sm:py-32 lg:grid-cols-[.65fr_1fr]"><div><span className="inline-flex rounded-full bg-[#f7cf58] px-4 py-2 text-[.64rem] font-extrabold uppercase tracking-[.14em]">Hỏi gì cũng được</span><h2 className="mt-6 text-5xl font-extrabold leading-[1.02] tracking-[-.04em] sm:text-7xl">Trước khi<br /><i className="font-serif font-medium text-[#e66e4c]">xách ba lô lên.</i></h2><p className="mt-5 max-w-md text-sm leading-7 text-[#21483d]/55">Thông tin rõ ràng để bạn chỉ cần tập trung vào phần vui nhất của chuyến đi.</p></div><div className="border-t-2 border-[#21483d]/12">{showcaseFaqs.map(([question,answer],index)=><details key={question} className="group border-b-2 border-[#21483d]/12 py-6"><summary className="flex cursor-pointer list-none items-center gap-4 font-extrabold"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white text-xs">0{index+1}</span><span className="flex-1">{question}</span><Plus className="h-5 w-5 transition group-open:rotate-45" /></summary><p className="ml-14 mt-4 max-w-2xl text-sm leading-7 text-[#21483d]/55">{answer}</p></details>)}</div></section>

    <section className="relative mx-auto min-h-[560px] w-[min(1380px,calc(100%-24px))] overflow-hidden rounded-[44px] bg-[#21483d] text-white"><Image src={conceptImages.detail2} alt="Không gian chung Lago - ảnh minh họa" fill sizes="100vw" className="object-cover opacity-32" /><div className="relative z-10 flex min-h-[560px] flex-col items-center justify-center px-6 text-center"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#f7cf58] text-[#21483d]"><Sun className="h-7 w-7" /></span><h2 className="mt-7 max-w-4xl text-5xl font-extrabold leading-[1.02] tracking-[-.04em] sm:text-7xl">Lên lịch cho những ngày<br /><i className="font-serif font-medium text-[#f7cf58]">thật vui nhé?</i></h2><Link href={`${config.basePath}/dat-phong`} className="mt-8 inline-flex min-h-14 items-center gap-3 rounded-full bg-white px-7 text-sm font-extrabold text-[#21483d]">Xem căn còn trống <ArrowRight className="h-4 w-4" /></Link></div></section>

    <TemplateFooter config={config} />
  </main>;
}
