import Image from "next/image";
import { ShowcaseLink as Link } from "@/features/showcase/site/showcase-link";
import { ArrowDownRight, ArrowRight, BedDouble, MapPin, Plus, Users } from "lucide-react";
import { ShowcaseSwitcher } from "@/features/showcase/components/showcase-switcher";
import { TemplateExperienceLayer } from "@/features/showcase/components/template-experience-layer";
import { TemplateTimeGreeting } from "@/features/showcase/components/template-time-greeting";
import { experienceMoments, guestStories, showcaseFaqs } from "@/features/showcase/data/showcase-content";
import { conceptImages, stays } from "@/features/stays/data/demo-data";
import { formatCurrency } from "@/shared/lib/format";
import { TemplateFooter, TemplateHeader, type CompleteTemplateConfig } from "@/features/showcase/site/complete-template-site";
import { SkipLink } from "@/shared/components/ui/skip-link";

export function TinhLangHome({ config }: { config: CompleteTemplateConfig }) {
  return <div className="showcase-root min-h-screen bg-[#faf3ea] text-[#17321d]">
    <SkipLink />
    <TemplateExperienceLayer mood="editorial" />
    <ShowcaseSwitcher current="tinh-lang" />
    <TemplateHeader config={config} />
    <main id="noi-dung-chinh" tabIndex={-1}>

    <section className="mx-auto grid min-h-[calc(100svh-76px)] w-[min(1420px,calc(100%-40px))] items-center gap-8 py-10 lg:grid-cols-[.82fr_1.18fr] lg:py-14">
      <div className="relative z-10 lg:pr-8"><TemplateTimeGreeting mood="editorial" /><p className="mt-5 text-[.65rem] font-bold uppercase tracking-[.24em] text-[#80613f]">LAKA ký sự · Số 01</p><h1 className="mt-8 font-serif text-[clamp(3.4rem,16vw,6.5rem)] font-medium leading-[.82] tracking-[-.065em] lg:text-[8rem]">Nghệ thuật<br /><i className="font-normal">sống thật chậm.</i></h1><p className="mt-10 max-w-md text-sm leading-7 text-[#17321d]/58">Bốn căn nhà giữa thiên nhiên, dành cho những ngày bạn muốn bước chậm lại và ở gần nhau hơn.</p><div className="mt-8 flex items-center gap-6"><Link href={`${config.basePath}/dat-phong`} className="inline-flex min-h-14 items-center gap-4 rounded-full bg-[#17321d] px-6 text-sm font-bold text-white">Tìm căn của bạn <ArrowRight className="h-4 w-4" /></Link><a href="#collection" aria-label="Cuộn đến bộ sưu tập" className="grid h-14 w-14 place-items-center rounded-full border border-[#17321d]/25"><ArrowDownRight className="h-5 w-5" /></a></div></div>
      <div className="relative min-h-[560px] lg:min-h-[720px]"><div className="absolute inset-y-0 right-0 w-[88%] overflow-hidden rounded-t-[220px]"><Image src={conceptImages.detail1} alt="Không gian LAKA phong cách tạp chí" fill priority sizes="(max-width:1024px) 100vw, 58vw" className="object-cover" /><div className="absolute inset-0 bg-[#17321d]/8" /></div><div className="absolute bottom-10 left-0 max-w-[230px] border border-[#17321d]/15 bg-[#faf3ea]/94 p-6 backdrop-blur"><p className="font-serif text-2xl leading-tight">“Một nơi để thời gian thôi thúc giục.”</p><p className="mt-5 text-[.58rem] font-bold uppercase tracking-[.18em] text-[#80613f]">Triết lý LAKA</p></div><span className="absolute right-5 top-5 rounded-full border border-white/50 bg-white/25 px-3 py-1.5 text-[.56rem] font-bold uppercase tracking-widest text-white backdrop-blur">Ảnh minh họa</span></div>
    </section>

    <section className="border-y border-[#17321d]/15 py-8"><div className="mx-auto grid w-[min(1420px,calc(100%-40px))] gap-5 text-center text-[.62rem] font-bold uppercase tracking-[.18em] text-[#17321d]/45 sm:grid-cols-3"><span>04 căn nhà riêng</span><span>Thiên nhiên bên ngoài · tiện nghi bên trong</span><span>Sống chậm · gần nhau hơn</span></div></section>

    <section id="collection" className="mx-auto w-[min(1420px,calc(100%-40px))] py-24 sm:py-32"><div className="grid items-end gap-8 lg:grid-cols-[1fr_.55fr]"><div><p className="text-[.65rem] font-bold uppercase tracking-[.18em] text-[#80613f]">Bộ sưu tập căn riêng</p><h2 className="mt-5 max-w-4xl font-serif text-5xl font-medium leading-[1.05] tracking-[-.035em] sm:text-7xl">Mỗi căn nhà,<br /><i>một khoảng riêng.</i></h2></div><p className="text-sm leading-7 text-[#17321d]/55">Chọn không gian theo người đồng hành, nhịp nghỉ và cách bạn muốn thức dậy mỗi sáng.</p></div>
      <div className="mt-16 grid gap-10 md:grid-cols-2">{stays.map((stay, index) => <Link href={`${config.basePath}/luu-tru/${stay.slug}`} key={stay.id} className={`group ${index % 2 ? "md:mt-24" : ""}`}><div className="relative aspect-[4/5] overflow-hidden bg-[#ded5c8]"><Image src={stay.image} alt={`${stay.name} - ảnh minh họa`} fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover transition duration-700 group-hover:scale-[1.025]" /><span className="absolute left-4 top-4 rounded-full bg-[#faf3ea]/92 px-3 py-1.5 text-[.58rem] font-bold uppercase tracking-wider">0{index + 1}</span></div><div className="mt-5 flex items-start justify-between gap-6 border-b border-[#17321d]/15 pb-5"><div><p className="text-[.6rem] font-bold uppercase tracking-[.18em] text-[#80613f]">{stay.location}</p><h3 className="mt-2 font-serif text-4xl font-medium tracking-[-.04em]">{stay.name}</h3><div className="mt-3 flex gap-4 text-xs text-[#17321d]/48"><span className="flex items-center gap-1.5"><Users className="h-3.5 w-3.5" />{stay.maxGuests}</span><span className="flex items-center gap-1.5"><BedDouble className="h-3.5 w-3.5" />{stay.bedrooms} phòng</span><span className="flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5" />{stay.highlights[0]}</span></div></div><div className="text-right text-[.62rem] uppercase tracking-wider text-[#17321d]/42">Từ<br /><strong className="mt-1 block text-sm text-[#17321d]">{formatCurrency(stay.basePrice)}</strong></div></div></Link>)}</div>
    </section>

    <section className="border-y border-[#17321d]/15 bg-[#e7ded1] py-24 sm:py-32"><div className="mx-auto grid w-[min(1420px,calc(100%-40px))] gap-14 lg:grid-cols-[.88fr_1.12fr] lg:items-center"><div className="relative aspect-[4/5] overflow-hidden"><Image src={conceptImages.experience} alt="Một ngày chậm tại LAKA - ảnh minh họa" fill sizes="(max-width:1024px) 100vw, 45vw" className="object-cover" /><span className="absolute bottom-5 left-5 bg-[#faf3ea] px-3 py-2 text-[.58rem] font-bold uppercase tracking-wider">Một ngày tại LAKA</span></div><div className="lg:pl-12"><p className="text-[.64rem] font-bold uppercase tracking-[.18em] text-[#80613f]">Nhịp ngày thật chậm</p><h2 className="mt-5 font-serif text-5xl font-medium leading-[1.05] tracking-[-.035em] sm:text-7xl">Một ngày không cần<br /><i>kế hoạch quá nhiều.</i></h2><div className="mt-10 border-t border-[#17321d]/15">{experienceMoments.slice(0,3).map(({time,title,text})=><article key={time} className="grid gap-3 border-b border-[#17321d]/15 py-6 sm:grid-cols-[70px_1fr]"><span className="text-xs font-bold text-[#80613f]">{time}</span><div><h3 className="font-serif text-2xl font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-[#17321d]/55">{text}</p></div></article>)}</div></div></div></section>

    <section className="mx-auto grid w-[min(1420px,calc(100%-40px))] gap-12 py-24 sm:py-32 lg:grid-cols-[.55fr_1fr]"><div><p className="text-[.64rem] font-bold uppercase tracking-[.18em] text-[#80613f]">Nhật ký của khách · 01</p><p className="mt-5 text-sm leading-7 text-[#17321d]/48">Những điều khách mang về sau chuyến đi thường không nằm trong danh sách tiện nghi.</p></div><blockquote><p className="font-serif text-4xl font-medium leading-[1.18] tracking-[-.025em] sm:text-6xl">“{guestStories[0].quote}”</p><footer className="mt-8 border-t border-[#17321d]/15 pt-5 text-xs font-bold uppercase tracking-[.14em] text-[#17321d]/45">{guestStories[0].name} · {guestStories[0].stay}</footer></blockquote></section>

    <section className="mx-auto w-[min(1120px,calc(100%-40px))] pb-24 sm:pb-32"><div className="mb-9 grid gap-5 sm:grid-cols-2 sm:items-end"><div><p className="text-[.64rem] font-bold uppercase tracking-[.18em] text-[#80613f]">Trước kỳ nghỉ</p><h2 className="mt-4 font-serif text-5xl font-medium tracking-[-.035em]">Một vài điều cần biết.</h2></div><Link href={`${config.basePath}/thong-tin`} className="justify-self-start border-b border-[#17321d] pb-1 text-xs font-bold sm:justify-self-end">Xem tất cả thông tin</Link></div><div className="border-t border-[#17321d]/15">{showcaseFaqs.map(([question,answer])=><details key={question} className="group border-b border-[#17321d]/15 py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-bold"><span>{question}</span><Plus className="h-5 w-5 shrink-0 transition group-open:rotate-45" /></summary><p className="mt-4 max-w-3xl text-sm leading-7 text-[#17321d]/55">{answer}</p></details>)}</div></section>

    <section className="mx-auto w-[min(1420px,calc(100%-24px))] bg-[#17321d] px-6 py-20 text-center text-white sm:px-12 sm:py-28"><p className="text-[.64rem] font-bold uppercase tracking-[.2em] text-[#dbc6a9]">Khoảng yên đang chờ</p><h2 className="mx-auto mt-6 max-w-4xl font-serif text-5xl font-medium leading-[1.08] tracking-[-.035em] sm:text-7xl">Để LAKA giữ lại<br /><i>một khoảng yên cho bạn.</i></h2><Link href={`${config.basePath}/dat-phong`} className="mt-9 inline-flex min-h-14 items-center gap-3 rounded-full bg-white px-7 text-sm font-bold text-[#17321d]">Chọn ngày lưu trú <ArrowRight className="h-4 w-4" /></Link></section>

    </main>
    <TemplateFooter config={config} />
  </div>;
}
