"use client";

import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { demoBookings } from "@/lib/demo-data";
import { formatCurrency } from "@/lib/format";
import { StatusBadge } from "./status-badge";

export function BookingTable(){const [query,setQuery]=useState("");const [status,setStatus]=useState("ALL");const rows=useMemo(()=>demoBookings.filter(b=>(status==="ALL"||b.status===status)&&`${b.guest} ${b.phone} ${b.code}`.toLowerCase().includes(query.toLowerCase())),[query,status]);return <div className="card mt-8 overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-lago-ink/40"/><input value={query} onChange={e=>setQuery(e.target.value)} className="input pl-10" placeholder="Tìm tên, số điện thoại, mã booking..."/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="input sm:w-48"><option value="ALL">Mọi trạng thái</option><option value="HELD">Chờ xác nhận</option><option value="CONFIRMED">Đã xác nhận</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-lago-cream/70 text-xs text-lago-ink/50"><tr><th className="px-5 py-3">Booking</th><th>Khách hàng</th><th>Lưu trú</th><th>Thời gian</th><th>Giá trị</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.map(b=><tr className="border-t border-lago-ink/5 hover:bg-lago-cream/40" key={b.code}><td className="px-5 py-4"><strong>{b.code}</strong><p className="mt-1 text-xs text-lago-ink/45">{b.created}</p></td><td><strong>{b.guest}</strong><p className="mt-1 text-xs text-lago-ink/45">{b.phone}</p></td><td>{b.stay}</td><td>{b.checkIn} → {b.checkOut}</td><td>{formatCurrency(b.total)}</td><td><StatusBadge status={b.status}/></td><td><button className="rounded-full border px-3 py-2 text-xs font-bold">Chi tiết</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-12 text-center text-sm text-lago-ink/50">Không có booking phù hợp.</div>}</div>}
