import { Clock3, Mail, MapPin, Phone, Settings2 } from "lucide-react";
import { AdminPageHeading } from "@/features/admin/components/page-heading";

export default function SettingsPage() {
  return <>
    <AdminPageHeading title="Thiết lập vận hành" description="Chỉ quản lý thông tin liên hệ và các thông số quan trọng dùng trong quy trình đặt chỗ." />
    <form className="mt-8 grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <section className="card p-6 sm:p-7"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-lago-mist"><Phone className="h-5 w-5" /></span><div><h2 className="font-bold">Thông tin liên hệ</h2><p className="mt-1 text-sm text-lago-ink/50">Thông tin khách dùng để gọi, nhắn Zalo và nhận hỗ trợ.</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Số điện thoại<input className="input mt-2" type="tel" inputMode="tel" defaultValue="0900 000 000" /></label><label className="text-sm font-bold">Số Zalo<input className="input mt-2" type="tel" inputMode="tel" defaultValue="0900000000" /></label><label className="text-sm font-bold sm:col-span-2">Email liên hệ<div className="relative mt-2"><Mail className="pointer-events-none absolute left-4 top-4 h-4 w-4 text-lago-ink/35" /><input className="input pl-11" type="email" defaultValue="hello@lagohomestay.vn" /></div></label><label className="text-sm font-bold sm:col-span-2">Địa chỉ<div className="relative mt-2"><MapPin className="pointer-events-none absolute left-4 top-4 h-4 w-4 text-lago-ink/35" /><input className="input pl-11" defaultValue="Địa chỉ sẽ được cập nhật" /></div></label></div></section>

      <section className="card p-6 sm:p-7"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-lago-cream"><Settings2 className="h-5 w-5" /></span><div><h2 className="font-bold">Quy tắc đặt chỗ</h2><p className="mt-1 text-sm text-lago-ink/50">Thông số áp dụng chung cho toàn bộ căn nhà.</p></div></div><div className="mt-7 grid gap-5"><label className="text-sm font-bold">Thời gian giữ chỗ<select className="input mt-2" defaultValue="120"><option value="60">1 giờ</option><option value="120">2 giờ</option><option value="720">12 giờ</option></select></label><div className="grid grid-cols-2 gap-4"><label className="text-sm font-bold">Giờ nhận căn<div className="relative mt-2"><Clock3 className="pointer-events-none absolute left-4 top-4 h-4 w-4 text-lago-ink/35" /><input className="input pl-11" type="time" defaultValue="14:00" /></div></label><label className="text-sm font-bold">Giờ trả căn<div className="relative mt-2"><Clock3 className="pointer-events-none absolute left-4 top-4 h-4 w-4 text-lago-ink/35" /><input className="input pl-11" type="time" defaultValue="11:00" /></div></label></div></div></section>

      <div className="xl:col-span-2"><button className="btn-primary" type="button">Lưu thiết lập</button><p className="mt-3 text-xs text-lago-ink/45">Nội dung giới thiệu, hình ảnh và SEO được quản lý trong mã nguồn, không chỉnh sửa tại CRM.</p></div>
    </form>
  </>;
}
